name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run Unit Tests
      run: |
        pytest tests/unit_test.py

    - name: Run Code Coverage
      run: |
        pytest --cov=app tests/

    - name: Run Integration Tests
      run: |
        pytest tests/integration_test.py

    - name: Database Tests
      run: |
        pytest tests/database_test.py

    - name: Linting
      run: |
        pip install flake8
        flake8 .
      continue-on-error: true
    
    - name: Code Formatting
      run: |
        pip install black
        black . --exclude "app\.py"
        
  security:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Security Tests
      run: |
        pip install bandit
        bandit -r app/
  database:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Database Tests
      run: |
        #tessting database
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to Production
      run: |
        #deploying to production
